name: Weekly Verra Sync

on:
  schedule:
    - cron: '0 9 * * 3'  # Every Wednesday at 9am UTC
  workflow_dispatch:

jobs:
  verra-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: uv sync

    - name: Install Playwright browsers
      run: uv run playwright install

    - name: Run download + diff script
      run: |
        mkdir -p logs
        uv run scripts/run_pipeline.py

    - name: Read log file
      id: log_content
      run: |
        LOG_FILE=$(ls -t logs/verra_*.log | head -n1)
        echo "Using latest log file: $LOG_FILE"
        cat $LOG_FILE > latest_log.txt

    - name: Create GitHub Issue
      uses: peter-evans/create-issue-from-file@v5
      with:
        title: "Verra Registry Update ${{ github.run_number }}"
        content-filepath: latest_log.txt
        token: ${{ secrets.GH_TOKEN }}
        labels: |
          automated
          verra-update

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add data/archive/* data/latest.csv logs/*
        git commit -m "Update Verra Registry data [skip ci]" || exit 0
        git push