name: Weekly Verra Sync

on:
  schedule:
    - cron: '0 9 * * 1'  # Every Wednesday at 9am UTC
  workflow_dispatch:

jobs:
  verra-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run download + diff script
      run: |
        mkdir -p logs
        python scripts/run_pipeline.py

    - name: Read log file
      id: log_content
      run: |
        LOG_FILE=$(ls -t logs/verra_*.log | head -n1)
        echo "Using latest log file: $LOG_FILE"
        cat $LOG_FILE > latest_log.txt

    - name: Push log to GitHub Issue
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: 1  # Replace with the issue number you want to use
        token: ${{ secrets.GH_TOKEN }}
        body-file: latest_log.txt